# Generated by Django 5.2.5 on 2025-08-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_remove_book_publication_year_book_publication_date_and_more'),
    ]

    operations = [
    ]
