# Generated by Django 5.2.5 on 2025-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_auto_20250831_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
